### ISSUE TITLE
Add black box behind text for better visibility

### ISSUE THREAD

**Issue by mlodato517** [deepgram-devs/jamfest#12]

**Comment by nikolawhallon** [comment]
I have a PR up here: https://github.com/deepgram-devs/jamfest/pull/14

**Comment by mlodato517** [comment]
Pro tip - if you update the PR description of #14 to say "This closes https://github.com/deepgram-devs/jamfest/pull/14" then GH will link the issue to the PR and when that PR gets merged this issue will automatically get closed.

**Comment by nikolawhallon** [comment]
These didn't automatically get closed when those PRs got merged :\

**Comment by mlodato517** [comment]
Yeah unfortunately you said "Maybe addresses https://github.com/deepgram-devs/jamfest/issues/12 maybe." instead of "This closes https://github.com/deepgram-devs/jamfest/issues/12". The "This closes" language is actually important. I unfortunately split my advice [across two issues](https://github.com/deepgram-devs/GarbageGame/issues/4#issuecomment-1323920948) but the automatic GitHub-issue-linker-closer looks for [specific phrases](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) and "addresses" is not one of them :-(
